name: Build Electron App

on:
  push:
    branches: [ master ] # Запускать при пуше в master
  pull_request:
    branches: [ master ] # Запускать при PR в master
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  build:
    runs-on: ${{ matrix.os }} # Запускать на разных ОС
    # Добавляем права на запись для коммитов и тегов
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Матрица для сборки под Linux и Windows
        node-version: [20.x] # Используем Node.js LTS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Загружаем код репозитория

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Кэшируем зависимости npm

      - name: Install dependencies
        run: npm ci # Используем npm ci для быстрой и надежной установки

      # Шаг для автоматического увеличения минорной версии (только для master)
      - name: Bump version and push tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        id: tag_version
        # Используем действия для автоматического тегирования и версионирования
        # Это действие увеличит минорную версию в package.json и создаст тег
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Токен для push тегов
          release_branches: master # Указываем ветку для релизов/тегов
          tag_prefix: "" # Убираем префикс v, если не нужен
          # Закомментировано: можно указать 'minor' явно, но по умолчанию он и так minor
          # default_bump: minor

      - name: Build Electron app
        run: npm run make # Запускаем команду сборки Electron Forge
        # env:
          # Токен GitHub для публикации артефактов (если нужно настроить публикацию)
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Можно добавить другие переменные окружения, если они нужны для сборки

      # Шаг для загрузки артефактов сборки (оставляем для скачивания из Actions)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-${{ matrix.os }} # Имя артефакта (например, electron-app-ubuntu-latest)
          # Путь к собранным файлам (обычно в папке out)
          # Проверьте ваш forge.config.ts или вывод `npm run make`, чтобы убедиться в правильности пути
          path: |
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.zip
            out/make/**/*.exe
            out/make/**/*.msi
            out/make/**/*.AppImage
            !out/make/**/RELEASES* # Исключаем файлы RELEASES, если они не нужны
          # retention-days: 5 # Опционально: сколько дней хранить артефакты
          if-no-files-found: warn # Предупреждать, если файлы не найдены, но не падать

      # ЗАМЕНЯЕМ СТАРЫЕ ШАГИ РЕЛИЗА НА ЭТОТ:
      - name: Create Release and Upload Assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2 # Используем этот action
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }} # Тег из шага версионирования
          name: Release ${{ steps.tag_version.outputs.new_tag }} # Имя релиза
          body: | # Описание релиза
            Автоматический релиз версии ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          prerelease: false
          # Указываем маску для файлов, которые нужно загрузить в релиз
          # Ищет все основные типы установочных файлов в папке out/make и ее подпапках
          files: |
            out/make/**/*.deb
            out/make/**/*.rpm
            out/make/**/*.zip
            out/make/**/*.exe
            out/make/**/*.msi
            out/make/**/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Токен обязателен

      # Старые шаги Create GitHub Release и Upload Release Assets УДАЛЕНЫ 